# fly.toml app configuration file generated for ncu on 2026-04-08T14:22:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ncu'
primary_region = 'lax'

[build]

[env]
  DATA_DIR = '/data'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'arf_data'
  destination = '/data'
  processes = ['app']

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
