/**
 * Creates all ops_* tables in PostgreSQL with proper types.
 * Run: DATABASE_URL=<url> npx tsx scripts/create-pg-ops-tables.ts
 */
import { Pool } from "pg";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const statements = [
  `CREATE TABLE IF NOT EXISTS ops_residents (
    id SERIAL PRIMARY KEY,
    facility_number TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    dob BIGINT,
    gender TEXT,
    ssn_last4 TEXT,
    admission_date BIGINT,
    discharge_date BIGINT,
    room_number TEXT,
    bed_number TEXT,
    primary_dx TEXT,
    secondary_dx TEXT,
    level_of_care TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    emergency_contact_relation TEXT,
    funding_source TEXT,
    regional_center_id TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_ops_res_facility ON ops_residents(facility_number)`,
  `CREATE INDEX IF NOT EXISTS idx_ops_res_status ON ops_residents(status)`,

  `CREATE TABLE IF NOT EXISTS ops_resident_assessments (
    id SERIAL PRIMARY KEY,
    resident_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    assessment_type TEXT NOT NULL,
    assessed_by TEXT NOT NULL,
    assessed_at BIGINT NOT NULL,
    bathing BOOLEAN DEFAULT FALSE,
    dressing BOOLEAN DEFAULT FALSE,
    grooming BOOLEAN DEFAULT FALSE,
    toileting BOOLEAN DEFAULT FALSE,
    continence BOOLEAN DEFAULT FALSE,
    eating BOOLEAN DEFAULT FALSE,
    mobility BOOLEAN DEFAULT FALSE,
    transfers BOOLEAN DEFAULT FALSE,
    meal_prep BOOLEAN DEFAULT FALSE,
    housekeeping BOOLEAN DEFAULT FALSE,
    laundry BOOLEAN DEFAULT FALSE,
    transportation BOOLEAN DEFAULT FALSE,
    finances BOOLEAN DEFAULT FALSE,
    communication BOOLEAN DEFAULT FALSE,
    cognition_score INTEGER,
    behavior_notes TEXT,
    fall_risk_level TEXT,
    vision TEXT,
    hearing TEXT,
    speech TEXT,
    ambulation TEXT,
    self_administer_meds BOOLEAN DEFAULT FALSE,
    next_due_date BIGINT,
    lic_form_number TEXT,
    raw_json TEXT,
    created_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_care_plans (
    id SERIAL PRIMARY KEY,
    resident_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    created_by TEXT NOT NULL,
    effective_date BIGINT NOT NULL,
    review_date BIGINT NOT NULL,
    goal TEXT NOT NULL,
    intervention TEXT NOT NULL,
    frequency TEXT NOT NULL,
    responsible_staff TEXT,
    digital_signature_resident TEXT,
    digital_signature_family TEXT,
    signature_date BIGINT,
    status TEXT NOT NULL DEFAULT 'draft',
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_daily_tasks (
    id SERIAL PRIMARY KEY,
    care_plan_id INTEGER NOT NULL,
    resident_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    task_name TEXT NOT NULL,
    task_type TEXT NOT NULL,
    scheduled_time TEXT,
    shift TEXT,
    assigned_to TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    completed_at BIGINT,
    completion_notes TEXT,
    refused BOOLEAN DEFAULT FALSE,
    refuse_reason TEXT,
    task_date BIGINT NOT NULL,
    created_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_medications (
    id SERIAL PRIMARY KEY,
    resident_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    drug_name TEXT NOT NULL,
    generic_name TEXT,
    dosage TEXT NOT NULL,
    route TEXT NOT NULL,
    frequency TEXT NOT NULL,
    scheduled_times TEXT,
    prescriber_name TEXT,
    prescriber_npi TEXT,
    rx_number TEXT,
    pharmacy_name TEXT,
    start_date BIGINT,
    end_date BIGINT,
    is_prn BOOLEAN DEFAULT FALSE,
    prn_indication TEXT,
    is_controlled BOOLEAN DEFAULT FALSE,
    is_psychotropic BOOLEAN DEFAULT FALSE,
    is_hazardous BOOLEAN DEFAULT FALSE,
    classification TEXT,
    requires_vitals_before BOOLEAN DEFAULT FALSE,
    vital_type TEXT,
    refill_threshold_days INTEGER DEFAULT 7,
    auto_refill_request BOOLEAN DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'active',
    discontinued_reason TEXT,
    discontinued_by TEXT,
    discontinued_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_med_passes (
    id SERIAL PRIMARY KEY,
    medication_id INTEGER NOT NULL,
    resident_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    scheduled_datetime BIGINT NOT NULL,
    administered_datetime BIGINT,
    administered_by TEXT,
    witness_by TEXT,
    right_resident BOOLEAN DEFAULT FALSE,
    right_medication BOOLEAN DEFAULT FALSE,
    right_dose BOOLEAN DEFAULT FALSE,
    right_route BOOLEAN DEFAULT FALSE,
    right_time BOOLEAN DEFAULT FALSE,
    right_reason BOOLEAN DEFAULT FALSE,
    right_documentation BOOLEAN DEFAULT FALSE,
    right_to_refuse BOOLEAN DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'pending',
    refusal_reason TEXT,
    hold_reason TEXT,
    notes TEXT,
    pre_vitals_bp TEXT,
    pre_vitals_pulse INTEGER,
    pre_vitals_temp DOUBLE PRECISION,
    pre_vitals_spo2 INTEGER,
    prn_reason TEXT,
    prn_effectiveness_noted_at BIGINT,
    prn_effectiveness_notes TEXT,
    created_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_controlled_sub_counts (
    id SERIAL PRIMARY KEY,
    medication_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    count_date BIGINT NOT NULL,
    shift TEXT NOT NULL,
    counted_by TEXT NOT NULL,
    witnessed_by TEXT NOT NULL,
    opening_count INTEGER NOT NULL,
    closing_count INTEGER NOT NULL,
    administered_count INTEGER NOT NULL DEFAULT 0,
    wasted_count INTEGER NOT NULL DEFAULT 0,
    discrepancy BOOLEAN DEFAULT FALSE,
    discrepancy_notes TEXT,
    resolved BOOLEAN DEFAULT FALSE,
    created_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_med_destruction (
    id SERIAL PRIMARY KEY,
    medication_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit TEXT NOT NULL,
    destruction_method TEXT NOT NULL,
    destroyed_by TEXT NOT NULL,
    witnessed_by TEXT NOT NULL,
    destruction_date BIGINT NOT NULL,
    reason TEXT NOT NULL,
    created_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_incidents (
    id SERIAL PRIMARY KEY,
    facility_number TEXT NOT NULL,
    resident_id INTEGER,
    incident_type TEXT NOT NULL,
    incident_date BIGINT NOT NULL,
    incident_time TEXT,
    location TEXT,
    description TEXT NOT NULL,
    immediate_action_taken TEXT,
    injury_involved BOOLEAN DEFAULT FALSE,
    injury_description TEXT,
    hospitalization_required BOOLEAN DEFAULT FALSE,
    hospital_name TEXT,
    reported_by TEXT NOT NULL,
    supervisor_notified BOOLEAN DEFAULT FALSE,
    supervisor_notified_at BIGINT,
    family_notified BOOLEAN DEFAULT FALSE,
    family_notified_at BIGINT,
    physician_notified BOOLEAN DEFAULT FALSE,
    physician_notified_at BIGINT,
    lic_624_required BOOLEAN DEFAULT FALSE,
    lic_624_submitted BOOLEAN DEFAULT FALSE,
    lic_624_submitted_at BIGINT,
    soc_341_required BOOLEAN DEFAULT FALSE,
    soc_341_submitted BOOLEAN DEFAULT FALSE,
    root_cause TEXT,
    corrective_action TEXT,
    follow_up_date BIGINT,
    follow_up_completed BOOLEAN DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'open',
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_leads (
    id SERIAL PRIMARY KEY,
    facility_number TEXT NOT NULL,
    contact_name TEXT NOT NULL,
    contact_phone TEXT,
    contact_email TEXT,
    contact_relation TEXT,
    prospect_name TEXT NOT NULL,
    prospect_dob BIGINT,
    prospect_gender TEXT,
    care_needs_summary TEXT,
    funding_source TEXT,
    desired_move_in_date BIGINT,
    referral_source TEXT,
    assigned_to TEXT,
    stage TEXT NOT NULL DEFAULT 'inquiry',
    lost_reason TEXT,
    notes TEXT,
    last_contact_date BIGINT,
    next_follow_up_date BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_tours (
    id SERIAL PRIMARY KEY,
    lead_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    scheduled_at BIGINT NOT NULL,
    completed_at BIGINT,
    conducted_by TEXT,
    outcome TEXT,
    notes TEXT,
    follow_up_action TEXT,
    created_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_admissions (
    id SERIAL PRIMARY KEY,
    lead_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    resident_id INTEGER,
    lic_601_completed BOOLEAN DEFAULT FALSE,
    lic_601_date BIGINT,
    lic_602a_completed BOOLEAN DEFAULT FALSE,
    lic_602a_date BIGINT,
    lic_603_completed BOOLEAN DEFAULT FALSE,
    lic_603_date BIGINT,
    lic_604a_completed BOOLEAN DEFAULT FALSE,
    lic_604a_date BIGINT,
    lic_605a_completed BOOLEAN DEFAULT FALSE,
    lic_605a_date BIGINT,
    lic_610d_completed BOOLEAN DEFAULT FALSE,
    lic_610d_date BIGINT,
    admission_agreement_signed BOOLEAN DEFAULT FALSE,
    admission_agreement_signed_at BIGINT,
    admission_agreement_signed_by TEXT,
    physician_report_received BOOLEAN DEFAULT FALSE,
    tb_test_results_received BOOLEAN DEFAULT FALSE,
    move_in_date BIGINT,
    move_in_completed BOOLEAN DEFAULT FALSE,
    assigned_room TEXT,
    welcome_completed BOOLEAN DEFAULT FALSE,
    notes TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_billing_charges (
    id SERIAL PRIMARY KEY,
    facility_number TEXT NOT NULL,
    resident_id INTEGER NOT NULL,
    charge_type TEXT NOT NULL,
    description TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    unit TEXT,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
    billing_period_start BIGINT,
    billing_period_end BIGINT,
    is_recurring BOOLEAN DEFAULT FALSE,
    recurrence_interval TEXT,
    prorated BOOLEAN DEFAULT FALSE,
    prorate_from BIGINT,
    prorate_to BIGINT,
    source TEXT NOT NULL DEFAULT 'manual',
    clinical_ref_id INTEGER,
    created_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_invoices (
    id SERIAL PRIMARY KEY,
    facility_number TEXT NOT NULL,
    resident_id INTEGER NOT NULL,
    invoice_number TEXT NOT NULL UNIQUE,
    billing_period_start BIGINT NOT NULL,
    billing_period_end BIGINT NOT NULL,
    subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax DOUBLE PRECISION NOT NULL DEFAULT 0,
    total DOUBLE PRECISION NOT NULL DEFAULT 0,
    amount_paid DOUBLE PRECISION NOT NULL DEFAULT 0,
    balance_due DOUBLE PRECISION NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft',
    due_date BIGINT,
    sent_at BIGINT,
    paid_at BIGINT,
    payment_method TEXT,
    payment_reference TEXT,
    notes TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_payments (
    id SERIAL PRIMARY KEY,
    invoice_id INTEGER NOT NULL,
    facility_number TEXT NOT NULL,
    resident_id INTEGER NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    payment_date BIGINT NOT NULL,
    payment_method TEXT NOT NULL,
    reference_number TEXT,
    type TEXT NOT NULL DEFAULT 'payment',
    notes TEXT,
    recorded_by TEXT,
    created_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_staff (
    id SERIAL PRIMARY KEY,
    facility_number TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    role TEXT NOT NULL,
    hire_date BIGINT,
    termination_date BIGINT,
    license_number TEXT,
    license_expiry BIGINT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_shifts (
    id SERIAL PRIMARY KEY,
    facility_number TEXT NOT NULL,
    staff_id INTEGER NOT NULL,
    shift_date BIGINT NOT NULL,
    shift_type TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    is_overtime BOOLEAN DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'scheduled',
    covered_by_id INTEGER,
    notes TEXT,
    created_at BIGINT NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS ops_facility_settings (
    id SERIAL PRIMARY KEY,
    facility_number TEXT NOT NULL,
    setting_key TEXT NOT NULL,
    setting_value TEXT,
    updated_at BIGINT NOT NULL,
    UNIQUE(facility_number, setting_key)
  )`,

  `CREATE TABLE IF NOT EXISTS ops_compliance_calendar (
    id SERIAL PRIMARY KEY,
    facility_number TEXT NOT NULL,
    item_type TEXT NOT NULL,
    description TEXT NOT NULL,
    due_date BIGINT NOT NULL,
    completed_date BIGINT,
    assigned_to TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    reminder_days_before INTEGER DEFAULT 30,
    created_at BIGINT NOT NULL
  )`,
];

async function main() {
  console.log(`[ops-schema] Creating ${statements.length} ops_* tables in PostgreSQL...`);
  for (const sql of statements) {
    const tableName = sql.match(/TABLE IF NOT EXISTS (\w+)/)?.[1] ?? sql.match(/INDEX IF NOT EXISTS (\w+)/)?.[1] ?? "?";
    await pool.query(sql);
    console.log(`  ✓ ${tableName}`);
  }
  const r = await pool.query("SELECT COUNT(*) as n FROM pg_tables WHERE schemaname='public'");
  console.log(`[ops-schema] Done. Total tables in PostgreSQL: ${r.rows[0].n}`);
  await pool.end();
}

main().catch(err => {
  console.error("[ops-schema] ERROR:", err.message);
  pool.end();
  process.exit(1);
});
